const checkListData = {
  test: [
    { id: 0, text: "Item 1", checked: false },
    { id: 1, text: "Item 2", checked: false },
    { id: 2, text: "Item 3", checked: false },
  ],
  dia: [
    { id: 0, text: "Générer le courrier d'accompagnement", checked: false },
    { id: 1, text: "Générer la DIA", checked: false },
    {
      id: 2,
      text: "Sur le courrier d'accompagnement : indiquer le numéro du recommandé",
      checked: false,
    },
    { id: 3, text: "Compléter la DIA", checked: false },
    { id: 4, text: "Vérifier les points complétés", checked: false },
    {
      id: 5,
      text: "Imprimer les pages 1 à 3 en 4 exemplaires",
      checked: false,
    },
    {
      id: 6,
      text: "Imprimer le courrier d'accompagnement en 1 seul exemplaire",
      checked: false,
    },
    {
      id: 7,
      text: "Signer + tampon sur le courrier d'accompagnement",
      checked: false,
    },
    { id: 8, text: "Signer + tampon sur les DIA", checked: false },
    {
      id: 9,
      text: "Scanner le courrier d'accompagner + 1 exemplaire de DIA",
      checked: false,
    },
    {
      id: 10,
      text: "Rattacher le scan au dossier informatique",
      checked: false,
    },
    {
      id: 11,
      text: "Vérifier que les 4 exemplaires sont complets et ont été signés",
      checked: false,
    },
    { id: 12, text: "Envoyer le courrier", checked: false },
  ],
  cu: [
    { id: 0, text: "Générer le courrier d’accompagnement", checked: false },
    { id: 1, text: "Générer la demande de CU", checked: false },
    {
      id: 2,
      text: "Sur le courrier d’accompagnement : indiquer le numéro de recommandé",
      checked: false,
    },
    { id: 3, text: "Compléter le certificat d’urbanisme", checked: false },
    { id: 4, text: "Vérifier les points complétés", checked: false },
    { id: 5, text: "Obtenir une copie du plan cadastral", checked: false },
    {
      id: 6,
      text: "Imprimer le plan cadastral en 2 exemplaires",
      checked: false,
    },
    {
      id: 7,
      text: "Imprimer la demande de CU en 2 exemplaires",
      checked: false,
    },
    {
      id: 8,
      text: "Imprimer le courrier d’accompagnement en 1 exemplaire",
      checked: false,
    },
    {
      id: 9,
      text: "Signer + tampon le courrier d’accompagnement",
      checked: false,
    },
    {
      id: 10,
      text: "Signer + tampon le courrier d’accompagnement",
      checked: false,
    },
    { id: 11, text: "Signer + tampon de la demande de CU", checked: false },
    {
      id: 12,
      text: "Scanner le courrier d’accompagnement + la demande de CU ",
      checked: false,
    },
    {
      id: 13,
      text: "Rattacher le scan au dossier informatique",
      checked: false,
    },
    {
      id: 14,
      text: "Vérifier que les 2 exemplaires sont complets et ont été signés",
      checked: false,
    },
    { id: 15, text: "Envoyer le courrier", checked: false },
  ],
  docusign: [
    {
      id: 1,
      text: "Pointer l'état-civil des parties : attention aux accents et aux tirets",
      checked: false,
    },
    {
      id: 2,
      text: "Si plusieurs signataires, dans la procuration : indiquer un ordre de signature",
      checked: false,
    },
  ],
  ehf: [
    {
      id: 1,
      text: "Noter les références cadastrales figurant dans le titre de propriété",
      checked: false,
    },
    {
      id: 2,
      text: "Noter les références cadastrales figurant dans le modèle 1",
      checked: false,
    },
    {
      id: 3,
      text: "Effectuer une demande d'hypothécaire sur l'ensemble des parcelles notées",
      checked: false,
    },
    {
      id: 4,
      text: "Si le bien est situé en copropriété, effectuer une demande sur l’assise sans les lots, + une demande sur l’assise aves les lots, idem si lot volume",
      checked: false,
    },
  ],
  decompte: [
    { id: 1, text: "Vérifier la date du rendez-vous", checked: false },
    { id: 2, text: "Vérifier l'heure du rendez-vous", checked: false },
    { id: 3, text: "Vérifier manuelement les calculs", checked: false },
    { id: 4, text: "Vérifier l'adresse du décompte", checked: false },
    {
      id: 5,
      text: "Vérifier l'existence d'une commission d'agence",
      checked: false,
    },
    {
      id: 6,
      text: "Vérifier l'existence d'une commission pour le courtier",
      checked: false,
    },
  ],
  formapuv: [
    {
      id: 1,
      text: "Vérifier si les codes AR24 ont été donnés à l'acquéreur",
      checked: false,
    },
    {
      id: 2,
      text: "Indiquer sur le dossier papier : la date de réitération (ctrl + F : seize)",
      checked: false,
    },
    {
      id: 3,
      text: "Indiquer sur le dossier papier : la date de l'obtention du prêt (ctrl + F : taux)",
      checked: false,
    },
    {
      id: 4,
      text: "Indiquer sur le dossier papier : le montant du dépôt de garantie",
      checked: false,
    },
    {
      id: 5,
      text: "Envoyer la copie de la promesse au vendeur",
      checked: false,
    },
    {
      id: 6,
      text: "Envoyer la copie de la promesse à l'agence",
      checked: false,
    },
    {
      id: 7,
      text: "Envoyer la copie de la promesse à l'acquéreur avec le mail d'usage",
      checked: false,
    },
    { id: 8, text: "Créer la notifcation SRU AR 24", checked: false },
    {
      id: 9,
      text: "Notification SRU : vérifier l'objet du mail : Mise en oeuvre faculté de rétractation",
      checked: false,
    },
    {
      id: 10,
      text: "Notification SRU : vérifier que la promesse de vente AVEC ANNEXES et jointe au mail",
      checked: false,
    },
    {
      id: 11,
      text: "Notification SRU : vérifier que l'ensemble des modificatifs / EDD-RCP sont joints au mail",
      checked: false,
    },
    { id: 12, text: "Envoyer la notification SRU", checked: false },
    {
      id: 13,
      text: "Créer une alerte Outlook pour la date d'obtention du prêt (J-20)",
      checked: false,
    },
    {
      id: 14,
      text: "Créer une alerte Outlook pour la date de réitération (J-20)",
      checked: false,
    },
    { id: 15, text: "Signer informatiquement l'acte", checked: false },
    {
      id: 16,
      text: "Créer le répertoire : indiquer la date de réitération",
      checked: false,
    },
    { id: 17, text: "Créer la fiche PERVAL", checked: false },
    {
      id: 18,
      text: 'Ranger le dossier dans la pile "En attente"',
      checked: false,
    },
    {
      id: 19,
      text: "Rajouter une alerte outlook dans les 10 jours pour versement du dépôt de garantie",
      checked: false,
    },
    {
      id: 20,
      text: "Créer les comptes en comptablités (compte primaire pour l'acquéreur, secondaire pour le vendeur",
      checked: false,
    },
    {
      id: 21,
      text: "Vérifier qui ouvre le dossier (ATTENTION ETAT-CIVIL DE NOS CLIENTS) : le cas échéant créer une alerte dans les 15 jours",
      checked: false,
    },
    {
      id: 23,
      text: "Si vente sur Paris : demande DHL",
      checked: false,
    },
    {
      id: 231,
      text: "Vérifier si demande de représentant fiscal (plus-value) à effectuer",
      checked: false,
    },
    {
      id: 24,
      text: "Scanner la convention d'honoraires",
      checked: false,
    },
    {
      id: 25,
      text: "Rattacher la convention d'honoraires au dossier informatique",
      checked: false,
    },
    {
      id: 26,
      text: "Créer une pochette minute pour la promesse de vente",
      checked: false,
    },
    {
      id: 27,
      text: "Imprimer la fiche signature, et l'inclure dans la pochette minute papier",
      checked: false,
    },
    { id: 28, text: "Classer la pochette minute", checked: false },
  ],
  analyseCompromisAgence: [
    { id: 1, text: "Vérifier le prix de vente", checked: false },
    { id: 2, text: "Vérifier l'existence ou nom de mobilier", checked: false },
    {
      id: 3,
      text: "Vérifier la commission d'agence, qui la paye",
      checked: false,
    },
    {
      id: 4,
      text: "Vérifier le montant du dépôt de garantie, qui est le dépositaire",
      checked: false,
    },
    {
      id: 5,
      text: "Vérifier si remboursement du prorata de taxe foncière",
      checked: false,
    },
    {
      id: 6,
      text: "Vérifier si remboursement du prorata des charges de copropriété",
      checked: false,
    },
    {
      id: 7,
      text: "Vérifier la date de prise en charge des travaux de copropriété",
      checked: false,
    },
    {
      id: 8,
      text: "Vérifier si remboursement du fonds travaux",
      checked: false,
    },
    { id: 9, text: "Vérifier la date de réitération", checked: false },
    { id: 10, text: "Vérifier la date d'obtention du prêt", checked: false },
    { id: 11, text: "Vérifier la date de signature", checked: false },
    { id: 12, text: "Vérifier si notaire en concours", checked: false },
  ],
  formaVente: [
    { id: 1, text: "Signer l'acte informatiquement", checked: false },
    { id: 2, text: "Générer répertoire informatique", checked: false },
    { id: 3, text: "Générer la fiche perval (envoyer)", checked: false },
    { id: 4, text: "Transmettre les virements internes", checked: false },
    { id: 5, text: "Transmettre les virements externes", checked: false },
    {
      id: 6,
      text: "Envoyer une copie AAE de l'acte aux parties par mail",
      checked: false,
    },
    { id: 7, text: "Vérifier que la pré-taxe a été établie", checked: false },
    {
      id: 8,
      text: "Si vente en copropriété : notification art 20 + art 6",
      checked: false,
    },
    { id: 9, text: "Pochette minute papier", checked: false },
    { id: 10, text: "Scanner le RIB des clients signés", checked: false },
    {
      id: 11,
      text: "Vérifier si mainlevée à effectuer: si oui, placer le dossier dans la pile mainlevée, créer une note sur le compte vendeur dans le logiciel de comptabilité",
      checked: false,
    },

    {
      id: 12,
      text: "Imprimer la fiche signature, et l'inclure dans la pochette minute papier",
      checked: false,
    },
    { id: 13, text: "Classer la pochette minute", checked: false },
  ],
  formaPret: [
    { id: 1, text: "Signer l'acte informatiquement", checked: false },
    { id: 2, text: "Générer répertoire informatique", checked: false },
    {
      id: 3,
      text: "Envoyer une copie AAE de l'acte aux parties par mail",
      checked: false,
    },
    { id: 4, text: "Notification de signature à la banque", checked: false },
    { id: 5, text: "Bordereau d'inscription hypothécaire", checked: false },
    {
      id: 6,
      text: "Vérifier que l'attestation d'assurance d'habitation figure au dossier",
      checked: false,
    },
    {
      id: 7,
      text: "Vérifier info assurance copropriété au dossier",
      checked: false,
    },
    {
      id: 8,
      text: "Imprimer la fiche signature, et l'inclure dans la pochette minute papier",
      checked: false,
    },
    { id: 9, text: "Classer la pochette minute", checked: false },
  ],
  clauseEtude: [
    {
      id: 1,
      text: "Désignation de l’immeuble / déclaration des parties concernant la désignation",
      checked: false,
    },
    { id: 2, text: "Plans des lots", checked: false },
    { id: 3, text: "Etat du bien", checked: false },
    { id: 4, text: "Modification salle d’eau / cuisine", checked: false },
    { id: 5, text: "Sanibroyeur", checked: false },
    { id: 6, text: "Assainissement", checked: false },
    { id: 7, text: "Entretien annuel chaudière", checked: false },
    { id: 8, text: "Entretien conduit cheminée", checked: false },
    { id: 9, text: "Bien destiné à la location", checked: false },
    { id: 10, text: "Situation des parcelles voisines", checked: false },
    {
      id: 11,
      text: "Sinistre pendant la durée de la promesse",
      checked: false,
    },
  ],
  minute: [
    {
      id: 1,
      text: "Choisir la pochette minute pour l'année en cours (2023 = bleue)",
      checked: false,
    },
    {
      id: 9,
      text: "Indiquer le numéro de dossier informatique",
      checked: false,
    },
    {
      id: 2,
      text: "Indiquer les initiales du clerc en charge du dossier",
      checked: false,
    },
    { id: 3, text: "Indiquer le nom du notaire participant", checked: false },
    {
      id: 4,
      text: "Indiquer si le notaire participant est présent ou non",
      checked: false,
    },
    { id: 10, text: "Indiquer la date de signature de l'acte", checked: false },
    {
      id: 5,
      text: "Indiquer le nom du dossier (ex: vente entre M. DUPONT et Mme PAUL)",
      checked: false,
    },
    {
      id: 6,
      text: "Indiquer les numéros des comptes comptables",
      checked: false,
    },
    { id: 7, text: "Cocher le lieu de l'étude", checked: false },
    { id: 8, text: "Ranger le dossier dans l'armoire", checked: false },
  ],
  fixationRdvVente: [
    {
      id: 1,
      text: "Vérifier que la notification SRU a été purgée",
      checked: false,
    },
    {
      id: 2,
      text: "Vérifier l'absence de droit de préemption urbain ou que la DIA a été purgée",
      checked: false,
    },
    {
      id: 3,
      text: "Vérifier l'absence de garantie hypothécaire ou accord de remboursement anticipé obtenu",
      checked: false,
    },
    {
      id: 4,
      text: "Vérifier les conditions suspensives de la PUV (ex: droit de préemption locataire)",
      checked: false,
    },
    {
      id: 412,
      text: "Vérifier si le diagnostic termites parties privatives est périmé",
      checked: false,
    },
    {
      id: 413,
      text: "Vérifier si l'ERP est périmé",
      checked: false,
    },
    {
      id: 414,
      text: "Vérifier si nous sommes en possession des actes de naissance / mariage des parties",
      checked: false,
    },
    {
      id: 5,
      text: "Vérifier si le vendeur doit fournir des documents (ex: factures, décenalle, etc)",
      checked: false,
    },
    {
      id: 6,
      text: "Relancer le syndic pour l'obtention de l'état daté et du certificat art 20-II : date de signature - 48h",
      checked: false,
    },
    {
      id: 7,
      text: "Créer une alerte pour relancer le syndic : date de signature - 48h",
      checked: false,
    },
  ],
  formaAntPuv: [
    { id: 1, text: "Vérifier l'état civil des parties", checked: false },
    {
      id: 2,
      text: "Si rdv en visioconférence : vérifier si nous sommes en possession des identifiants du confrère ou si les indentifiants du confrère ont été transmis",
      checked: false,
    },
    { id: 3, text: "Vérifier AAE", checked: false },
    {
      id: 4,
      text: "Transmettre le projet d'acte aux parties (avec les diags et les 3 derniers PV d'AG)",
      checked: false,
    },
    {
      id: 5,
      text: "Transmettre le projet d'acte au confrère (avec les annexes)",
      checked: false,
    },
    {
      id: 6,
      text: "Vérifier si le projet AAE est prêt (signature des mandataires)",
      checked: false,
    },
    {
      id: 7,
      text: "Si signature à distance, vérifier que le projet AAE été correctement préparé",
      checked: false,
    },
    {
      id: 8,
      text: "Compléter et imprimer la convention d'honoraires",
      checked: false,
    },
    {
      id: 9,
      text: "Envoyer le mail digicode aux parties + l'agence",
      checked: false,
    },
  ],
  formaAntVente: [
    { id: 1, text: "Vérification TRACFIN", checked: false },
    { id: 2, text: "Vérification Gels des avoirs", checked: false },
    { id: 3, text: "Attestation de provenance des fonds", checked: false },
    {
      id: 4,
      text: "Télé@ctes : Vérifier les actes de naissance des parties",
      checked: false,
    },
    {
      id: 5,
      text: "Télé@ctes : Vérifier les actes de mariage des parties",
      checked: false,
    },
    {
      id: 6,
      text: "Télé@ctes : Vérifier le modèle 1 : références cadastrales",
      checked: false,
    },
    {
      id: 7,
      text: "Télé@ctes : Vérifier le modèle 1 : numéro de lots / tantièmes",
      checked: false,
    },
    { id: 8, text: "Télé@ctes : Vérifier EHF : effet-relatif", checked: false },
    { id: 9, text: "Télé@ctes : Vérifier EHF : RCP/EDD", checked: false },
    { id: 10, text: "Vérifier AAE", checked: false },
    {
      id: 11,
      text: "Vérifier le nom des signataires dans le projet AAE (mandataires)",
      checked: false,
    },
    {
      id: 12,
      text: "Si signature à distance, vérifier que le projet AAE a été correctement préparé",
      checked: false,
    },
    {
      id: 13,
      text: "Préparer l'attestation de vente sans prix",
      checked: false,
    },
    {
      id: 14,
      text: "Préparer l'attestation de vente avec prix",
      checked: false,
    },
    { id: 15, text: "Préparer l'attestation de vente CARREZ", checked: false },
    { id: 16, text: "Préparer le décompte des proratas", checked: false },
    { id: 161, text: "Envoyer le projet d'acte aux parties", checked: false },
    { id: 162, text: "Envoyer le projet d'acte au confrère", checked: false },
    { id: 17, text: "Etablir la pré-taxe", checked: false },
    {
      id: 18,
      text: "Si signature à distance, adresser les identifiants au confrère / parties",
      checked: false,
    },
    {
      id: 19,
      text: "Envoyer le mail digicode aux parties + l'agence",
      checked: false,
    },
    { id: 20, text: "Pointer la réception des fonds", checked: false },
    {
      id: 21,
      text: "Vérifier si nous sommes en possession des factures de l'agence / courtier",
      checked: false,
    },
    {
      id: 22,
      text: "Préparer les pièces comptables : virement interne acquéreur -> vendeur",
      checked: false,
    },
    {
      id: 23,
      text: "Préparer les pièces comptables : virement externe vendeur -> vendeur / confrère",
      checked: false,
    },
    {
      id: 24,
      text: "Préparer les pièces comptables : virement externe vendeur -> vendeur",
      checked: false,
    },
    {
      id: 25,
      text: "Préparer les pièces comptables : virement externe agence / courtier",
      checked: false,
    },
  ],
  formaAntPret: [
    {
      id: 1,
      text: "Vérifier que nous sommes en possession de l'offre de prêt signée",
      checked: false,
    },
    {
      id: 2,
      text: "Vérifier que nous sommes en possession des informations relatives aux dates d'échéances",
      checked: false,
    },
    {
      id: 3,
      text: "Vérifier dans l'acte le montant des prêts",
      checked: false,
    },
    { id: 4, text: "Vérifier dans l'acte la durée des prêts", checked: false },
    { id: 5, text: "Vérifier dans l'acte le taux des prêts", checked: false },
    {
      id: 6,
      text: "Vérifier dans l'acte les dates d'échéances des prêts",
      checked: false,
    },
    {
      id: 7,
      text: "Télé@ctes : Vérifier les actes de naissance des parties",
      checked: false,
    },
    {
      id: 8,
      text: "Télé@ctes : Vérifier les actes de mariage des parties",
      checked: false,
    },
    {
      id: 9,
      text: "Télé@ctes : Vérifier le modèle 1 : références cadastrales",
      checked: false,
    },
    {
      id: 10,
      text: "Télé@ctes : Vérifier le modèle 1 : numéro de lots / tantièmes",
      checked: false,
    },
    {
      id: 11,
      text: "Télé@ctes : Vérifier EHF : effet-relatif",
      checked: false,
    },
    { id: 12, text: "Télé@ctes : Vérifier EHF : RCP/EDD", checked: false },
    {
      id: 123,
      text: "Si plus-value, établir la déclaration de plus-value démartérialisée",
      checked: false,
    },
    { id: 13, text: "Vérifier AAE", checked: false },
    {
      id: 14,
      text: "Vérifier le nom des signataires dans le projet AAE (mandataires)",
      checked: false,
    },
    { id: 141, text: "Envoyer le projet d'acte aux parties", checked: false },
    { id: 15, text: "Etablir la pré-taxe", checked: false },
    { id: 16, text: "Pointer la réception des fonds", checked: false },
    { id: 16, text: "Envoyer le mail digicode aux parties", checked: false },
  ],
  soldeCompte: [
    {
      id: 1,
      text: "FRAIS DOSSIER CONFRERE : si note non présente dans minute lors de la taxe, relancer clerc et mettre message dans compte",
      checked: false,
    },
    {
      id: 2,
      text: "CONCOURS : Vérifier si le ccrs a bien été proposé et payé au confrère",
      checked: false,
    },
    {
      id: 3,
      text: "CESSION ANTERIORITE : Normalement message sur minute avec post-it si doute demander aux formalités (VEFA AVEC PRET)",
      checked: false,
    },
    {
      id: 4,
      text: "VERIFICATION COMPTE DE TOUTES LES PARTIES A L’ACTE : dans les ventes vérification si compte vendeur soldé, si solde créditeur voir le clerc et voir pour faire solde",
      checked: false,
    },
    {
      id: 5,
      text: "VERIFICATION SI LE CLIENT N’A PAS UN OU DES SOLDES DEBITEUR",
      checked: false,
    },
    {
      id: 7,
      text: "MENTION SUR MINUTE : lors du traitement du solde s’il manque le RIB, frais dossier ou autre mettre mention S/R",
      checked: false,
    },
    {
      id: 8,
      text: "DOSSIER COMPLEXE : si on ne solde pas le dossier et qu’on fait remonter le solde à faire au clerc mettre un message avec la date dans le compte",
      checked: false,
    },
  ],
  taxeVente: [
    {
      id: 1,
      text: "Montant du prix (attention si charge augmentative du prix)",
      checked: false,
    },
    { id: 2, text: "Vérifier si bien en copropriété ou non", checked: false },
    { id: 3, text: "Vérifier si le bien est loué", checked: false },
    { id: 4, text: "Vérifier si plus-value immobilière", checked: false },
    {
      id: 5,
      text: "Vérifier si confrère en participation (attention si notaire de banque)",
      checked: false,
    },
    { id: 6, text: "Vérifier le nombre de pages", checked: false },
    { id: 7, text: "Vérifier si soumis au forfait", checked: false },
  ],
  demandeSoldeDebiteur: [
    {
      id: 1,
      text: "Vérifier l’absence de note dans le logiciel de comptabilité (ex : mainlevée)",
      checked: false,
    },
    {
      id: 2,
      text: "Vérifier que le relevé de compte est joint au mail",
      checked: false,
    },
    {
      id: 3,
      text: "Vérifier que le RIB de l’étude est joint au mail",
      checked: false,
    },
    { id: 4, text: "Vérifier que l’adresse mail du client", checked: false },
    { id: 5, text: "Compléter le montant du solde débiteur", checked: false },
  ],
  // { id: 1, text: "", checked: false },
};

export default checkListData;
